<a href="https://colab.research.google.com/github/Machinelearningdiscord/Machine-learning/blob/master/Numpy_ecer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Create an array of 10 zeros

#create an array of 10 ones

#create an array of 10 fives

#create an array of the integers from 10 to 50


#create an array of all the even integers from 10 to 50

#create a 3*3 matrix with values ranging from 0 to 8

#Use numpy to generate a random number bteween 0 and 1

#use numpy to generate an array of 35 random numbers sampled from a standard normal distribution

#Create an array of 20 linearly spaced points between 0 and 1


#array([[ 1,  2,  3,  4,  5],
#       [ 6,  7,  8,  9, 10],
#       [11, 12, 13, 14, 15],
#       [16, 17, 18, 19, 20],
#       [21, 22, 23, 24, 25]])
#Use above matrix to reproduce below matrix
#array([[12, 13, 14, 15],
#       [17, 18, 19, 20],
#       [22, 23, 24, 25]])
#grab number "20" from matrix mat

#Use above matrix(mat) to reproduce below matrix
#array([[ 2],
#       [ 7],
#       [12]])
#Get sum of all the values in mat
#Get standard deviation of all the values in the mat
#Get the sum of all of the columns in mat